{% set name = "flask-swagger-ui" %}
{% set version = "3.25.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flask-swagger-ui-{{ version }}.tar.gz
  sha256: 42d098997e06b04f992609c4945cc990738b269c153d8388fc59a91a5dfcee9e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - flask
    - python >=3.7

test:
  imports:
    - flask_swagger_ui
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sveint/flask-swagger-ui
  summary: Swagger UI blueprint for Flask
  license: MIT
  license_file: flask_swagger_ui/LICENSE

extra:
  recipe-maintainers:
    - xhochy
    - ukaratay
