travis:
  secure:
    BINSTAR_TOKEN: ZX6qOIocSRRnDuH3rKbQERVREmgB4BB3EbdlszVIzYBdML1fPv4MBTkBskzJSusjLcUkxVA/wNVl9NUppjyydYjHQYP783ohoLH+n43E7rmdkzpjkDBR0iHvDzfoMCfncgesB689KtT8kAaF7DpQYqNsukIkLstdlrD95q/Kk8gQ6OaMQjAYWpW0jaKMIuwZuHdJ8wpQS3vu31TjJGTBrNXXNMjmw6y245OMZzMYpTw1d/ATBko2gicq+fubJE/CvteZBklw6LH56FsOZ4deJi3aIxtQquKY2O2bDYdd1nRIhtt3HWl5EwzMMzkFPWpps6jZ26SsYq4T0O9kGf5d4lvF5leAizpViwpn6Qf0QB27fT6jp30wT6FSCS+MkPiuL/NusSQneK1N7OX8b/pS0StCbK60VgV7n2CK3b4n/U0FGSqmbGKd4QoKF3bYKdqrkhF/U2XGfM8nKBAvg0DHVbSY/B9VMlPdl5nTO1c7GV2CwHfzwhal2BCMm9dKoRxUSFOj5u+7nfcpVARp4vb1OiLT0ASlDElOdeCut3x3bUV7lpo8qC2PrCQNbg2KKbHD2GQyTS2lQbGRiWMURwv9Sbm4yL5fTdn7PBlr4IvYx1Fjs4ZNsZKJ1xEl49WoGWmPmmM68tFsKAXdSezG6am2IJAad9SBn0y3B5GngO74dWw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
