travis:
  secure:
    BINSTAR_TOKEN: OGa9MXFXyboF69CxgA984g3jNpOHpWeXNBgpWkAcERfn4pJnsRVLWN3wucYqnJzpNTSjRuC1rjtsU4pYGzNT97YZUNYf4cL/YwVyViKV9tqhrMPBWmGG58MuHVcrsz03D2H+8Np077/oFfIqHZVozXZEgVbMKs3oGt/n7tRaQvLhfNm2Tu802VsXmXzfX5xAc425HSnnE8XJpHC37Bgn4r9pclCR6K5c/OsBFT5FZQ4K8xJtl/n2zjrRPAHNEU0p4MVfGdwnM9XonQiCJR1lCmsI3yqHL8JthVRNWXZcP0ojDf5ue63kcXIm2mn2IGgjKTTkYLultEb0l5zCVacsMiDr2ztV7e3weeZUKh7AMB4ALO5K04bf5FWgbc5XBplibRIvxRxRakGios64Rlg6VP9Sl3lihVfZ21AqU/gRmTfQWd2p12j+Aqr5jUfqFi8JEwH/VxRAQmqLFvnAAvnlalxvvNoPBwWJcDfXxnzmeaYWFkY8Fw++rucNmp//Pf8XDImFxgpWMtZ62DSBB5pblbHxjq9axuy0EOHXdWO2F344eDR3fvFWVqnZCEh2AxdgfA83kxIBBBSBaSymd3QSMpU/D2LnnVCDWofKZXTjBib36s6LuaUkO4P8I1X6/s5Ewm/16zSorPHKZHdAJwf3W8eFdIviKlHTvElVSkCAHto=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
